import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="header-bar">
          <nav className="header-nav">
            <div className="header-logo">
              <img src="/logo.png" alt="Logo Clean & Garden" style={{ height: 70 }} />
            </div>
            <ul className="header-menu">
              <li><a href="#">Inicio</a></li>
              <li><a href="#">Servicios</a></li>
              <li><a href="#">Sobre Nosotros</a></li>
              <li><a href="#">Galería</a></li>
              <li><a href="#">Agenda tu hora</a></li>
            </ul>
            <a href="#" className="header-btn">
              Regístrate o inicia sesión
            </a>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
